module.exports.ambulanceinfos = require('./ambulanceInfos.models');
//module.exports.AdminSchemas = require('./AdminSchemas.models');
module.exports.DriverRegister = require('./driverRegister.models');
module.exports.license = require('./license.models');
module.exports.Personal_Id = require('./personal_Id.models');
module.exports.Revenue = require('./Revenue.model');
module.exports.UserRegister = require('./userRegister.model');
module.exports.userCard = require('./userCard.model');
module.exports.appAboutSchema = require('./AboutUs.model');
module.exports.UserCanMsg = require('./userCanclemsg.model');
module.exports.userTrans = require('./trans.model');
module.exports.Payment = require('./payment.model');
module.exports.adminl = require('./adminl.models');
module.exports.ambutype = require('./ambulancetype.models');
module.exports.bookamb = require('./bookingtab.models');
module.exports.hospitalRegister = require('./hospitalRegister.model');
module.exports.hospital_details= require('./hospital_details.model')
module.exports.hospitalUser = require('../model/hospitalUser.model');
module.exports.category = require('../model/category.model');
module.exports.subCategory = require('../model/subCategory.model')
module.exports.Notification = require("./notification");

//module.exports.Add_Hospital = require('./');